#!/usr/bin/env node
/**
 * Generates `data/sample_profiles.csv` — a synthetic dataset in exactly the
 * same 77-column format as the supplied file.
 *
 * Why this exists
 * ---------------
 * The dataset handed out with the task is real personal data: names, employers,
 * schools, and (in columns this app deliberately ignores) email addresses,
 * phone numbers, street addresses and birth dates. It is fine to work with
 * locally, but it should not be committed to a public repository.
 *
 * So the repo ships a synthetic stand-in instead. Vocabularies — skills, job
 * titles, companies, schools, industries, locations — are sampled from the real
 * file, because those are public, non-personal facts about the labour market
 * and they keep search behaviour realistic. Every *person* is then generated by
 * random recombination against invented names, so no row corresponds to a real
 * individual.
 *
 * The output deliberately reproduces the source file's quirks (Python-literal
 * cells, a duplicated header, a couple of injected grep lines) so the ETL's
 * repair path is exercised by the sample too.
 *
 * Usage:  node scripts/make-sample.mjs [count]
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const DB = path.join(root, 'backend/data/profiles.db');
const OUT = path.join(root, 'data/sample_profiles.csv');
const COUNT = Number(process.argv[2] ?? 120);

if (!fs.existsSync(DB)) {
  console.error(`Need the ingested database first:\n  npm run ingest\n(looked for ${DB})`);
  process.exit(1);
}

// --- deterministic RNG, so re-running produces an identical sample -----------
let seed = 20260902;
const rand = () => {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff;
  return seed / 0x7fffffff;
};
const pick = (list) => list[Math.floor(rand() * list.length)];
const pickMany = (list, min, max) => {
  const n = min + Math.floor(rand() * (max - min + 1));
  const out = new Set();
  for (let i = 0; i < n * 3 && out.size < n; i += 1) out.add(pick(list));
  return [...out];
};
const int = (min, max) => min + Math.floor(rand() * (max - min + 1));

// --- vocabularies drawn from the real data (non-personal facts) --------------
const db = new Database(DB, { readonly: true });
const col = (sql) => db.prepare(sql).all().map((r) => r.v).filter(Boolean);

const SKILLS = col(`SELECT s.name AS v FROM profile_skills ps JOIN skills s ON s.id = ps.skill_id
                    GROUP BY s.name HAVING COUNT(*) > 1 ORDER BY COUNT(*) DESC LIMIT 400`);
const TITLES = col(`SELECT DISTINCT job_title AS v FROM profiles WHERE job_title IS NOT NULL LIMIT 200`);
const COMPANIES = col(`SELECT DISTINCT company_name AS v FROM profiles WHERE company_name IS NOT NULL LIMIT 200`);
const SCHOOLS = col(`SELECT DISTINCT school AS v FROM educations WHERE school IS NOT NULL LIMIT 200`);
const INDUSTRIES = col(`SELECT DISTINCT industry AS v FROM profiles WHERE industry IS NOT NULL LIMIT 60`);
const LOCATIONS = col(`SELECT DISTINCT location_name AS v FROM profiles WHERE location_name IS NOT NULL LIMIT 120`);
const ROLES = col(`SELECT DISTINCT job_title_role AS v FROM profiles WHERE job_title_role IS NOT NULL LIMIT 30`);
const DEGREES = ['bachelors', 'masters', 'associates', 'doctorates', 'bachelor of science', 'master of business administration'];
const LEVELS = ['senior', 'manager', 'director', 'vp', 'cxo', 'owner', 'entry', 'partner'];
db.close();

// --- invented people ---------------------------------------------------------
const FIRST = ['ava','liam','noor','mateo','sana','yusuf','elena','kofi','mira','tomas','aisha','dario','lena','omar','ines','ravi','clara','felix','nadia','hugo','leila','pablo','zara','ivan','maya','arjun','freya','samir','nina','oscar','rania','luca','dana','emil','tara','bruno','sofia','kian','vera','anton'];
const LAST = ['okoro','marek','delgado','haddad','novak','fontaine','iversen','abiola','castellan','rahimi','vogel','santoro','bergman','nakamura','moreau','petrov','oyelaran','lindqvist','ferrara','koval','banda','stefani','ruiz','halvorsen','mensah','duarte','kaminski','soltani','ericsson','baptiste','varga','odonnell','schreiber','ibarra','lindberg','mwangi','pereira','strand','aubert','kozlov'];

/** Serialises a JS value the way Python's `str()` would. */
const py = (v) => {
  if (v === null || v === undefined) return 'None';
  if (v === true) return 'True';
  if (v === false) return 'False';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(v)) return `[${v.map(py).join(', ')}]`;
  return `{${Object.entries(v).map(([k, x]) => `'${k}': ${py(x)}`).join(', ')}}`;
};

/** RFC 4180 field. */
const cell = (v) => {
  const s = v === null || v === undefined ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const HEADER = ['full_name','first_name','last_name','gender','linkedin_url','linkedin_username','linkedin_id','facebook_url','facebook_username','facebook_id','industry','job_title','job_title_role','job_title_levels','job_company_id','job_company_name','job_company_website','job_company_size','job_company_founded','job_company_industry','job_company_linkedin_url','job_company_linkedin_id','job_company_facebook_url','job_company_twitter_url','job_company_location_name','job_company_location_locality','job_company_location_metro','job_company_location_region','job_company_location_geo','job_company_location_country','job_company_location_continent','job_last_updated','job_start_date','location_name','location_locality','location_metro','location_region','location_country','location_continent','location_geo','location_last_updated','linkedin_connections','inferred_salary','inferred_years_experience','summary','phone_numbers','emails','interests','skills','location_names','regions','countries','street_addresses','experience','education','profiles','certifications','languages','version_status','work_email','job_company_location_street_address','job_company_location_postal_code','job_summary','location_street_address','location_postal_code','middle_initial','middle_name','birth_year','birth_date','twitter_url','twitter_username','github_url','github_username','mobile_phone','location_address_line_2','job_title_sub_role','job_company_location_address_line_2'];

const SALARIES = ['45,000-55,000', '55,000-70,000', '70,000-85,000', '85,000-100,000', '100,000-150,000', '>250,000'];

function makeRow(i) {
  const first = pick(FIRST);
  const last = pick(LAST);
  const full = `${first} ${last}`;
  const slug = `${first}-${last}-${1000 + i}`;

  const title = pick(TITLES);
  const company = pick(COMPANIES);
  const industry = pick(INDUSTRIES);
  const location = pick(LOCATIONS);
  const parts = location.split(',').map((s) => s.trim());
  const skills = pickMany(SKILLS, 6, 30);
  const years = int(2, 30);

  const experience = Array.from({ length: int(1, 4) }, (_, k) => ({
    company: {
      name: k === 0 ? company : pick(COMPANIES),
      size: pick(['1-10', '11-50', '51-200', '201-500', '1001-5000']),
      industry: pick(INDUSTRIES),
      location: { name: pick(LOCATIONS) },
    },
    location_names: [location],
    end_date: k === 0 ? null : `${2024 - k * 3}-0${int(1, 9)}`,
    start_date: `${2024 - (k + 1) * 3}-0${int(1, 9)}`,
    title: {
      name: k === 0 ? title : pick(TITLES),
      role: pick(ROLES),
      sub_role: null,
      levels: rand() > 0.6 ? [pick(LEVELS)] : [],
    },
    is_primary: k === 0,
    summary: null,
  }));

  const education = Array.from({ length: int(1, 2) }, () => ({
    school: { name: pick(SCHOOLS), type: 'post-secondary institution', location: { name: pick(LOCATIONS) } },
    end_date: String(int(1990, 2020)),
    start_date: String(int(1986, 2016)),
    gpa: null,
    degrees: pickMany(DEGREES, 1, 2),
    majors: pickMany(['engineering', 'business administration', 'computer science', 'political science', 'nursing', 'psychology'], 1, 2),
    minors: [],
    summary: null,
  }));

  const row = Object.fromEntries(HEADER.map((h) => [h, '']));
  Object.assign(row, {
    full_name: full,
    first_name: first,
    last_name: last,
    gender: pick(['male', 'female', '']),
    linkedin_url: `linkedin.com/in/${slug}`,
    linkedin_username: slug,
    linkedin_id: String(100000000 + i * 7919),
    industry,
    job_title: title,
    job_title_role: pick(ROLES),
    job_title_levels: py(rand() > 0.6 ? [pick(LEVELS)] : []),
    job_company_id: company.replace(/[^a-z0-9]+/g, '-'),
    job_company_name: company,
    job_company_size: pick(['1-10', '11-50', '51-200', '201-500', '1001-5000']),
    job_company_industry: industry,
    job_start_date: `${2024 - int(1, 12)}-0${int(1, 9)}`,
    location_name: location,
    location_locality: parts[0] ?? '',
    location_region: parts.length > 2 ? parts[1] : '',
    location_country: parts[parts.length - 1] ?? '',
    location_continent: 'north america',
    linkedin_connections: `${int(80, 4000)}.0`,
    inferred_salary: pick(SALARIES),
    inferred_years_experience: `${years}.0`,
    summary: `${title.replace(/\b\w/g, (c) => c.toUpperCase())} at ${company.replace(/\b\w/g, (c) => c.toUpperCase())}. ${int(2, 20)} years across ${industry}.`,
    // Contact columns are left empty on purpose: this app never reads them, and
    // a sample dataset has no business carrying them even as fiction.
    phone_numbers: '[]',
    emails: '[]',
    interests: py(pickMany(['hiking', 'chess', 'travel', 'photography', 'cycling', 'history', 'music'], 0, 4)),
    skills: py(skills),
    location_names: py([location]),
    regions: py(parts.length > 2 ? [parts[1]] : []),
    countries: py([parts[parts.length - 1] ?? '']),
    street_addresses: '[]',
    experience: py(experience),
    education: py(education),
    profiles: py([{ network: 'linkedin', id: String(100000000 + i * 7919), url: `linkedin.com/in/${slug}`, username: slug }]),
    certifications: '[]',
    languages: py([{ name: 'english', proficiency: null }]),
    version_status: py({ status: 'updated', contains: [], previous_version: '12.0', current_version: '13.0' }),
  });

  return HEADER.map((h) => cell(row[h])).join(',');
}

const lines = [HEADER.join(',')];
for (let i = 0; i < COUNT; i += 1) {
  lines.push(makeRow(i));
  // Reproduce the source file's defects so the ETL repair path is covered:
  // an injected grep line, and a duplicated header halfway through.
  if (i === Math.floor(COUNT / 3)) {
    lines.push(String.raw`H:\New folder\leak\international\linkedin\part-00001.csv(2293): Specialties: sample defect`);
  }
  if (i === Math.floor(COUNT / 2)) {
    lines.push(HEADER.join(','));
  }
}

fs.writeFileSync(OUT, `${lines.join('\n')}\n`);
console.log(`✓ wrote ${OUT} — ${COUNT} synthetic profiles (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
